<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon />
    <AssemblyName>SimpleWPFGame</AssemblyName>
    <RootNamespace>SimpleWPFGame</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release</Configurations>
    <Configuration Condition="'$(Configuration)'==''">Debug</Configuration>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\charsettings.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="gamesettings.cfg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
